parameters:
  export_datatable_directory: '%kernel.project_dir%/files/export-datatable'
services:
  Webmen\DataTableBundle\DataTableBuilder:
    shared: false

  Webmen\DataTableBundle\DataTableFactory:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@translator'
      - '@service_container'
    shared: false
    public: true

  Webmen\DataTableBundle\DataTableExportAdapter:
    arguments:
      - '@translator'
      - '@security.helper'
      - '%export_datatable_directory%'
    shared: false
    public: true

  Webmen\DataTableBundle\Column\BoolType:
    shared: false
    public: true

  Webmen\DataTableBundle\Column\DateTimeType:
    shared: false
    public: true

  Webmen\DataTableBundle\Column\TextType:
    shared: false
    public: true

  Webmen\DataTableBundle\Column\TwigType:
    arguments:
      - '@twig'
    shared: false
    public: true

  Webmen\DataTableBundle\Filter\BoolFilterType:
    arguments:
      - '@translator'
    shared: false
    public: true

  Webmen\DataTableBundle\Filter\SimpleChoiceFilterType:
    shared: false
    public: true

  Webmen\DataTableBundle\Filter\SmartChoiceFilterType:
    shared: false
    public: true

  Webmen\DataTableBundle\Filter\TextFilterType:
    shared: false
    public: true

  Webmen\DataTableBundle\Modal\DefaultModalType:
    arguments:
      - '@twig'
      - '@translator'
    shared: false
    public: true
